@startuml
participant Server as ":server" <<javaScript>>
participant RouterA as ":auth" <<router>>
participant ControllerA as ":auth" <<controllers>>

note left of Server: Logout (GET)
[-> Server: req.get('/auth/logout')
activate Server
Server -> RouterA: app.use('/auth', auth)
activate RouterA
RouterA -> ControllerA: logout
activate ControllerA
ControllerA --> Server: response
deactivate ControllerA
Server -->]: response
deactivate Server
@enduml
